// src/students.js
export const GROUPS = [
  "ቡድን 1: ቤተ አውታር",
  "ቡድን 2: ቤተ በርኩማ",
  "ቡድን 3: ቤተ መቃኛ",
  "ቡድን 4: ቤተ እንዚራ",
];

export const STUDENTS = [
  // ------------------ ቡድን 1: ቤተ አውታር ------------------
  { name: "ኢየሱሩሳሌም ንጉሴ", englishName: "eyerusalem nigusse ", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ፍቅርተ ምስጋናው", englishName: "fikirte misganaw", group: "ቡድን 1: ቤተ አውታር" },
  { name: "እድላዊት ሲሳይ", englishName: "edlawoit sisay", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ትግስት ከንዴ", englishName: "tigist kende", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ህሊና ፍቃዱ", englishName: "hilina fekadu fekade", group: "ቡድን 1: ቤተ አውታር" },
  { name: "መክሊት ዱባለ", englishName: "meklit dubale", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ፋሲል ፍራንኮ", englishName: "fasil franko", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቅዱስ ታደሰ", englishName: "kidus tadese", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ዮሐንስ አባይ", englishName: "yohannes abay", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አደራጀው መልኬ", englishName: "aderajew melke", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ኢብሳ ተሬሳ", englishName: "ibsa teresa", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አንተነህ አየለ", englishName: "anteneh ayele", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ናሆም ሰለሞን", englishName: "nahom solomon", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ብርሃኑ ቦንጋ", englishName: "birhanu bonga", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ትዕግስት አሰፋ", englishName: "tigist assefa", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ነጻነት በኃይሉ", englishName: "netsanet behailu", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አጸደማርያም ጋሹ", englishName: "Atsedemariyam gashu", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ስምረት መኮንን", englishName: "simret mekonnen", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቤተልሔም ታደሰ", englishName: "betlehem tadese betelhem", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሔለን ሙላት", englishName: "helen mulat", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሲና ተስፋዬ", englishName: "sina tesfaye", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቃልኪዳን ኢሳያስ", englishName: "kalkidan isayas", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሲናዊት ጌትነት", englishName: "sinawit getnet", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ምልእልተጸጋ አዳነ", englishName: "mlelttsega adane", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ገነት ይትባረክ", englishName: "genet yitbarek", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ያለም ወርቅ አበራ", englishName: "yalem werk abera", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ኤልዳና እሸቱ", englishName: "eldana eshetu", group: "ቡድን 1: ቤተ አውታር" },


  { name: "አማናዊት ዳዊት", englishName: "amanawit dawit", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሳሮን ዳንኤል", englishName: "saron daniel", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሰላማዊት ቸርነት", englishName: "selamawit chernet", group: "ቡድን 1: ቤተ አውታር" },
  { name: "በጽናት ሙሉጌታ", englishName: "betsinat mulugeta", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ትርሃስ ገብረመድህን", englishName: "tirhas gebremedhin", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ትእግስት ወርቁ", englishName: "tigist werku", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቤርሳቤህ ዳንኤል", englishName: "bersabeh daniel", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቤተልሄም መኮንን", englishName: "betlehem mekonnen", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሄራን ጌታቸው", englishName: "heran getachew", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ሩት ብርሃነ", englishName: "rut birhane ruth", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ማህደር ተክለወይኒ", englishName: "mahder tek leweyni", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አርያም ጌታቸው", englishName: "aryam getachew", group: "ቡድን 1: ቤተ አውታር" },
  { name: "በረከት ስንዴው", englishName: "bereket sindew", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቤተልሄም መላኩ", englishName: "betlehem melaku", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ቢታኒያ መላኩ", englishName: "bitaniya melaku", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ያምሮት ተፈሪ", englishName: "yamrot teferi", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አይናለም ታደሰ", englishName: "aynalem tadese", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አለም ሀይሌ", englishName: "alem hayle", group: "ቡድን 1: ቤተ አውታር" },
  { name: "ማህሌት ሀይሌ", englishName: "mahlet haile", group: "ቡድን 1: ቤተ አውታር" },
  { name: "የሺወርቅ ሞላ", englishName: "yeshiwerk mola", group: "ቡድን 1: ቤተ አውታር" },
  { name: "አዛርያስ ብርሃኑ", englishName: "azarias birhanu", group: "ቡድን 1: ቤተ አውታር" },



  // ------------------ ቡድን 2: ቤተ በርኩማ ------------------
  { name: "አበባየሁ ወሰን", englishName: "abebayehu wesen", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ኤልቤተል ብንያም", englishName: "elbetel biniyam", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "መክሊት መንገሻ", englishName: "meklit mangesha", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "አርሴማ ቴወድሮስ", englishName: "arsema tewodros", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "አፎሚያ አማረ", englishName: "afomiya amare", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ቤተሩታዊት የሽበር", englishName: "beterutawit yeshiber", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሀና እስክንድር", englishName: "hana eskindir", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ቃልኪዳን ሀይሌ", englishName: "kalkidan hayle", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሀይማኖት ጌታ", englishName: "haymanot geta", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "መልካሙ ቆጭቶ", englishName: "melkamu kochito", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "አማኑኤል ኪዳነ", englishName: "amanuel kidane", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሚካኤል ተፈራ", englishName: "mikael tefera michael", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "እዮብ ደረሰ", englishName: "eyob derese iyob", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "አትናቴዎስ ጠና", englishName: "atnatewos tena", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ትግስት በለጠ", englishName: "tigist belete", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሰናይት ታከለ", englishName: "senait takele", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሀና ምህረት", englishName: "hana mihret", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ረድኤት ሰይፉ", englishName: "rediet seifu", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "በፀሎት አለቤ", englishName: "betselot alebe", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሰላማዊት አየለ", englishName: "selamawit ayele", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ብርቱካን አለሙ", englishName: "birtukan alemu", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሳራ ደምሴ", englishName: "sara demisse", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሒሩት መዝገቡ", englishName: "hirut mezgebu", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ጽዮን ካህሳይ", englishName: "tsion kahsay tsiyon", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሜሮን ካህሳይ", englishName: "meron kahsay", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "መክሊት ወ/ሚካኤል", englishName: "meklit w/mikael wolde mikael", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ትግስት አበባው", englishName: "tigist abebaw", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሠላም ፀጋዬ", englishName: "selam tsegaye", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ልእልት ክንፈ", englishName: "leilt kinfe", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ዮርዳኖስ ገ/ጊዮርጊስ", englishName: "yordanos gebregiorgis", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሄርሜላ ደምረዉ", englishName: "hermela demrew", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሰላማዊት ደፋር", englishName: "selamawit defar", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ዮርዳኖስ ስንታየሁ", englishName: "yordanos sintayehu", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ማራማዊት ግርማ", englishName: "maramawit girma", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ፍሬህይወት ሲሳይ", englishName: "frehiwot sisay", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "መዓዛ ቀለሙ", englishName: "meaza kelemu", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "መግደላዊት ጉግሳ", englishName: "megdelawit gugsa", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ይዲዲያ ፍቅሩ", englishName: "yididiya fekadu fekru", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "አዶናዊት ደበበ", englishName: "adonawit debebe", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ዮሐና ተስፉ", englishName: "yohanna tesfa", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ዊንታ ዮሐንስ", englishName: "winta yohannes", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ሜሮን ደሞዜ", englishName: "meron demoze", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ጽዮን ተስፉዬ", englishName: "tsion tesfaye tsiyon", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "የብርዘርፍ ደሳለኝ", englishName: "yebrzerf desalegh", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ኤዶም ሰሎሞን", englishName: "edom solomon", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ያለምወርቅ", englishName: "yalemwerk", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "ዮርዳኖስ ዘውዴ", englishName: "yordanos zewde", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "መልካም ተስፋ", englishName: "melkam tesfa", group: "ቡድን 2: ቤተ በርኩማ" },
  { name: "አቤኔዘር እንዳሸው", englishName: "abenezer endashew", group: "ቡድን 2: ቤተ በርኩማ" },

  // ------------------ ቡድን 3: ቤተ መቃኛ ------------------
  { name: "በእምነት እጥናው", englishName: "beemnet etinaw", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ዳግማዊት ሰለሞን", englishName: "dagmawit solomon", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ረድኤት ዳመና", englishName: "rediet damena", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ማህሌት ደበበ", englishName: "mahlet debebe", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ትዕግስት ፈንታሁን", englishName: "tigist fentahun", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አዲስአለም ደሳለኝ", englishName: "addisalem desalegh", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ትዕግስት ዮሐንስ", englishName: "tigist yohannes", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "በእምነት መንገሻ", englishName: "beemnet mengesha", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ብርክቲ አለሙ", englishName: "birkiti alemu", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ሳምራዊት ፀጋዬ", englishName: "samrawit tsegaye", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ሀና ነጋ", englishName: "hana nega hanna", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቅድስት ዮሐንስ", englishName: "kidist yohannes", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቃልኪዳን ጤናው", englishName: "kalkidan tenaw", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ፍርቱና ሲሳይ", englishName: "firtuna sisay", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "እሌኒ ክንፈ", englishName: "eleni kinfe", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ብሌን ሄኖክ", englishName: "blen henok belen", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቃልኪዳን ደቻሳ", englishName: "kalkidan dechasa", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ሜሮን አበበ", englishName: "meron abebe", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ትርሲት አለም", englishName: "tirsit alem", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አልአዛር ሚካኤል", englishName: "alazar mikael michael", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ናትናኤል መንግስቱ", englishName: "natnael mengistu nathanael", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ፋኑኤል አውራሪስ", englishName: "fanuel awraris", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ያሬድ ሰብስቤ", englishName: "yared sebsibe", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "መሉጌታ አስማማው", englishName: "mulugeta asmamaw", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "በርናባስ አለሙ", englishName: "barnabas alemu", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ዳንኤል ሚካኤል", englishName: "daniel mikael michael", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ፍቅር ይገርማል", englishName: "fikir yigermal", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አናቤል ሰለሞን", englishName: "anabel solomon annabel", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አማኑኤል ኢሳያስ", englishName: "amanuel isayas", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ማህሌት ሳልልህ", englishName: "mahlet salilih", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ማህሌት አለማየሁ", englishName: "mahlet alemayehu", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ይዲዲያ ክንፈ", englishName: "yididiya kinfe", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ፍቅር አያልነህ", englishName: "fikir ayalneh", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ሶሊያና አያልነህ", englishName: "soliyana ayalneh", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ሄለን መስፍን", englishName: "helen mesfin", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "የአብስራ ማሙዬ", englishName: "yeabsira mamuye", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ምዕራፍ ገ/ስላሴ", englishName: "meraf gebreselassie", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ዮርዳኖስ ፍቅሬ", englishName: "yordanos fekadu fekre", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አማናዊት አሸናፊ", englishName: "amanawit ashenafi", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ብስራት እሸቴ", englishName: "bisrat eshete", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቤዛ አብይ", englishName: "beza abiy", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አፎሚያ ሰለሞን", englishName: "afomiya solomon", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቤተልሄም ተካ", englishName: "betlehem teka", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ማርያማዊት ቸርነት", englishName: "maryamawit chernet", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "መሰረት ገብሬ", englishName: "meseret gebre", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "አላይት ክንፈ", englishName: "alayit kinfe", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ኤልሻዳይ ገንዘቡ", englishName: "elshaday genzebu", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ኢየሩሳሌም ሰይድ", englishName: "iyerusalem seyid yerusalem", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ያኔት ገነነ", englishName: "yanet genene", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቤተልሄም ሰለሞን", englishName: "betlehem solomon", group: "ቡድን 3: ቤተ መቃኛ" },
  { name: "ቤዛዊት ሄኖክ", englishName: "bezawit henok", group: "ቡድን 3: ቤተ መቃኛ" },

  // ------------------ ቡድን 4: ቤተ እንዚራ ------------------
  { name: "ሰላማዊት አየለጨቡዴ", englishName: "selamawit ayeleChebude", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "አቅሊሊያ ፊቅሩ", englishName: "akliliya fekru", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "አምራን አሰፋ", englishName: "amran assefa", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ኤልዳና ጤናዬ", englishName: "eldana tenaye", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ህሊና ዳንኤል", englishName: "hilina daniel", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ገነት አምሳሉ", englishName: "genet amsalu", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "አዲስ አታላይ", englishName: "addis atalay", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ፍሬህይወት አበጀ", englishName: "frehiwot abeje", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሶልያና ደበበ", englishName: "soliyana debebe", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሸሚዳ መሀመድ ኑር", englishName: "shemida mohammed nur", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "አለምነሽ ሀይሉ", englishName: "alemnesh haylu", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ቅዱስ ሁናቸው", englishName: "kidus hunachew", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "እንድርያስ ሳህሌ", englishName: "endriyas sahle andrew", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ቅዱስ ሳህሌ", englishName: "kidus sahle", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሽመልስ አጋ", englishName: "shimelis aga", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ዲ. እዮብ በየነ", englishName: "deacon eyob beyene iyob", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሮባ ሀብታሙ", englishName: "roba habtamu", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "በታንያ መላኩ", englishName: "betaniya melaku bethany", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ቃልአብ ጥላዬ", englishName: "kalab tilaye", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ፍፁም አባይነህ", englishName: "fitsum abayneh", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "እስጢፋኖስ ብርሃኑ", englishName: "estifanos birhanu stephen", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "የሽወርቅ ሞላ", englishName: "yeshiwerk mola", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ዶ/ር ዕዱላ ኪዳነ", englishName: "dr edula kidane", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "እሌኒ ክንዴ", englishName: "eleni kinde", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "የሸመቤት ዝናቡ", englishName: "yeshemebet zinabu", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ፋሲካ መስፍን", englishName: "fasika mesfin", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሀና ሰለሞን", englishName: "hana solomon hanna", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ማህሌት ተሾመ", englishName: "mahlet teshome", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ትግስት ደስታ", englishName: "tigist desta", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ፀጋነሽ ከበደ", englishName: "tseganesh kebede", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሐና ኤፍሬም", englishName: "hana efrem hanna", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ፍሬነሽ ወ/ሰማያት", englishName: "frenesh wolde semayat", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "መታሰቢያ ሰጥአርጌ", englishName: "metasebiya setarge", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ትርሲት አዝመራው", englishName: "tirsit azmeraw", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሐረግ ባንቴ", englishName: "hareg bante", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "በፀሎት በለጠ", englishName: "betselot belete", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ንጽሕት ስዩም", englishName: "ntsihit seyoum", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሜሮን ቢሽና", englishName: "meron bishna", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሰርካለም አሳየ", englishName: "serkalem asaye", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "መአዛ በቀለ", englishName: "meaza bekele", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "እሌኒ አስናቀ", englishName: "eleni asnake", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "መአዛነሽ ተስፋዉ", englishName: "meazanesh tesfaye tesfaw", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ሩሃማ መኮንን", englishName: "ruhama mekonnen", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "ቅድስት አለማየሁ", englishName: "kidist alemayehu", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "የምስራች አለሙ", englishName: "yemisrach alemu", group: "ቡድን 4: ቤተ እንዚራ" },
  { name: "አዶኒያስ ሳህሌ", englishName: "adoniyas sahle", group: "ቡድን 4: ቤተ እንዚራ" },




    { name: "እየሩሳሌም ሰኢድ", englishName: "Eyerusalem seid", group: "ቡድን 4: ቤተ እንዚራ" },
    
    { name: "ዝናሽ አሰፋ", englishName: "Zinash Asefa", group: "ቡድን 4: ቤተ እንዚራ" },

     { name: "ማህደር ቶሎሳ", englishName: "mahder tolosa", group: "ቡድን 4: ቤተ እንዚራ" },

    { name: "አለም ጌቱ", englishName: "alem getu", group: "ቡድን 4: ቤተ እንዚራ" },

    { name: "አማኑኤል ዘለቀ", englishName: "amanuel zeleke", group: "ቡድን 4: ቤተ እንዚራ" },

    { name: "ፍሬህይወት አብይ", englishName: "frehiwot abiy", group: "ቡድን 4: ቤተ እንዚራ" },
    { name: "የሺእመቤት ዘጎባ", englishName: "yeshiemebet zegoba", group: "ቡድን 4: ቤተ እንዚራ" },
      
   
 { name: "ሀና ነጋ", englishName: "hana nega", group: "ቡድን 4: ቤተ በርኩማ" },




];